name: Create a release branch from release tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - '!v[0-9]+.[0-9]+.rc*'

jobs:
  prepare-release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user information
        run: |
          git config user.name "GitHub Actions[bot]"
          git config user.email "<>"
          git checkout -b ${{ github.ref_name }}
      - name: Create VERSION file.
        run: '{ "version": "${{ github.ref_name }}", "hash": "{{ github.sha }}" } > VERSION'
      - name: Prepare CHANGELOG for version
        run: |
          echo "change\nchange2" > VERSION_CHANGELOG
      - name: Create release PR
        run: |
          git add VERSION
          git commit -m "prepare release ${{ github.ref_name }}"
          git push --force origin refs/heads/${{ github.ref_name }}
          git tag -f ${{ github.ref_name }}
          git push --force --tags origin
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create release
        run: |
          gh release create -F VERSION_CHANGELOG ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
