name: Create a release branch from release tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - '!v[0-9]+.[0-9]+.rc*'

jobs:
  prepare-release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup git user information
        run: |
          git config user.name "GitHub Actions[bot]"
          git config user.email "<>"
          git checkout -b ${{ github.ref_name }}
      - name: Create VERSION file.
        run: 'echo ${{ github.ref_name }} > VERSION'
      - name: Prepare CHANGELOG for version
        run: |
          echo "change\nchange2" > VERSION_CHANGELOG
      - name: Create release PR
        run: |
          git add VERSION
          git commit -m "prepare release ${{ github.ref_name }}"
          git push --force origin refs/heads/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create release
        run: |
          gh release create -d -F VERSION_CHANGELOG --target refs/heads/${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

#update-dependencies:
#  name: Update dependencies
#  runs-on: ubuntu-latest

#  steps:
#    - uses: actions/checkout@v3

#    # Checkout the depot tools they are needed by roll_deps.sh
#    - name: Checkout depot tools
#      run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

#    - name: Update PATH
#      run: echo "./depot_tools" >> $GITHUB_PATH

#    - name: Download dependencies
#      run: python3 utils/git-sync-deps


#    - name: Update dependencies
#      run: |
#        utils/roll_deps.sh
#        if [[ `git diff HEAD..origin/main --name-only | wc -l` == 0 ]]; then
#          echo "changed=false" >> $GITHUB_OUTPUT
#        else
#          echo "changed=true" >> $GITHUB_OUTPUT
#        fi
#      id: update_dependencies
#   
#    - name: Push changes and create PR
#      if: steps.update_dependencies.outputs.changed == 'true'
#      run: |
#        git push --force --set-upstream origin roll_deps
#        gh pr create --label 'kokoro:run' --base main -f -r s-perron
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
